version: "3.8"
services:
  mysql:
    image: mysql:5.7
    # Uncomment below when on Mac M1
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025