<?php

namespace ContainerELZ3IMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPIBWEYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RPIBWEY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RPIBWEY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CarController::delete' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController::edit' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController::index' => ['privates', '.service_locator.3LuXUDl', 'get_ServiceLocator_3LuXUDlService', true],
            'App\\Controller\\CarController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarController::show' => ['privates', '.service_locator.2lTRklS', 'get_ServiceLocator_2lTRklSService', true],
            'App\\Controller\\CarPartController::delete' => ['privates', '.service_locator.zh6TZt9', 'get_ServiceLocator_Zh6TZt9Service', true],
            'App\\Controller\\CarPartController::edit' => ['privates', '.service_locator.zh6TZt9', 'get_ServiceLocator_Zh6TZt9Service', true],
            'App\\Controller\\CarPartController::index' => ['privates', '.service_locator.raXW2PH', 'get_ServiceLocator_RaXW2PHService', true],
            'App\\Controller\\CarPartController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarPartController::show' => ['privates', '.service_locator.yRMtD6O', 'get_ServiceLocator_YRMtD6OService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.RtUoSKI', 'get_ServiceLocator_RtUoSKIService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CarController:delete' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController:edit' => ['privates', '.service_locator.KNAnNql', 'get_ServiceLocator_KNAnNqlService', true],
            'App\\Controller\\CarController:index' => ['privates', '.service_locator.3LuXUDl', 'get_ServiceLocator_3LuXUDlService', true],
            'App\\Controller\\CarController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarController:show' => ['privates', '.service_locator.2lTRklS', 'get_ServiceLocator_2lTRklSService', true],
            'App\\Controller\\CarPartController:delete' => ['privates', '.service_locator.zh6TZt9', 'get_ServiceLocator_Zh6TZt9Service', true],
            'App\\Controller\\CarPartController:edit' => ['privates', '.service_locator.zh6TZt9', 'get_ServiceLocator_Zh6TZt9Service', true],
            'App\\Controller\\CarPartController:index' => ['privates', '.service_locator.raXW2PH', 'get_ServiceLocator_RaXW2PHService', true],
            'App\\Controller\\CarPartController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CarPartController:show' => ['privates', '.service_locator.yRMtD6O', 'get_ServiceLocator_YRMtD6OService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.RtUoSKI', 'get_ServiceLocator_RtUoSKIService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CarController::delete' => '?',
            'App\\Controller\\CarController::edit' => '?',
            'App\\Controller\\CarController::index' => '?',
            'App\\Controller\\CarController::new' => '?',
            'App\\Controller\\CarController::show' => '?',
            'App\\Controller\\CarPartController::delete' => '?',
            'App\\Controller\\CarPartController::edit' => '?',
            'App\\Controller\\CarPartController::index' => '?',
            'App\\Controller\\CarPartController::new' => '?',
            'App\\Controller\\CarPartController::show' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CarController:delete' => '?',
            'App\\Controller\\CarController:edit' => '?',
            'App\\Controller\\CarController:index' => '?',
            'App\\Controller\\CarController:new' => '?',
            'App\\Controller\\CarController:show' => '?',
            'App\\Controller\\CarPartController:delete' => '?',
            'App\\Controller\\CarPartController:edit' => '?',
            'App\\Controller\\CarPartController:index' => '?',
            'App\\Controller\\CarPartController:new' => '?',
            'App\\Controller\\CarPartController:show' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
