<?php

namespace ContainerELZ3IMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YRMtD6OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yRMtD6O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yRMtD6O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'carPart' => ['privates', '.errored..service_locator.yRMtD6O.App\\Entity\\CarPart', NULL, 'Cannot autowire service ".service_locator.yRMtD6O": it needs an instance of "App\\Entity\\CarPart" but this type has been excluded in "config/services.yaml".'],
        ], [
            'carPart' => 'App\\Entity\\CarPart',
        ]);
    }
}
