<?php

namespace ContainerELZ3IMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarPart2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zh6TZt9.App\Entity\CarPart' shared service.
     *
     * @return \App\Entity\CarPart
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zh6TZt9": it needs an instance of "App\\Entity\\CarPart" but this type has been excluded in "config/services.yaml".');
    }
}
