<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xAzx5E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xAzx5E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4xAzx5E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4xAzx5E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4xAzx5E\App_KernelDevDebugContainer([
    'container.build_hash' => '4xAzx5E',
    'container.build_id' => '78ba33e3',
    'container.build_time' => 1691071110,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xAzx5E');
