<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBWtEALB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBWtEALB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBWtEALB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBWtEALB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBWtEALB\App_KernelDevDebugContainer([
    'container.build_hash' => 'BWtEALB',
    'container.build_id' => '3c08e630',
    'container.build_time' => 1690818244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBWtEALB');
