<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELZ3IMd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELZ3IMd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELZ3IMd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELZ3IMd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELZ3IMd\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELZ3IMd',
    'container.build_id' => 'd62d15ff',
    'container.build_time' => 1690471797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELZ3IMd');
