<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_car_index' => [[], ['_controller' => 'App\\Controller\\CarController::index'], [], [['text', '/car/list']], [], [], []],
    'app_car_add' => [[], ['_controller' => 'App\\Controller\\CarController::new'], [], [['text', '/car/add']], [], [], []],
    'app_car_show' => [['id'], ['_controller' => 'App\\Controller\\CarController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/car']], [], [], []],
    'app_car_edit' => [['id'], ['_controller' => 'App\\Controller\\CarController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/car']], [], [], []],
    'app_car_delete' => [['id'], ['_controller' => 'App\\Controller\\CarController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/car']], [], [], []],
    'app_car_part_index' => [[], ['_controller' => 'App\\Controller\\CarPartController::index'], [], [['text', '/car_part/']], [], [], []],
    'app_car_part_new' => [[], ['_controller' => 'App\\Controller\\CarPartController::new'], [], [['text', '/car_part/new']], [], [], []],
    'app_car_part_show' => [['id'], ['_controller' => 'App\\Controller\\CarPartController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/car_part']], [], [], []],
    'app_car_part_edit' => [['id'], ['_controller' => 'App\\Controller\\CarPartController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/car_part']], [], [], []],
    'app_car_part_delete' => [['id'], ['_controller' => 'App\\Controller\\CarPartController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/car_part']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_about' => [[], ['_controller' => 'App\\Controller\\HomeController::about'], [], [['text', '/about']], [], [], []],
    'app_user_profile' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/profile']], [], [], []],
];
